spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间为30m，可选
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.kzh.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080

